// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiMi5J51n7gYBMAdmPeof3YYD5k0HVR3s',
    appId: '1:813260456344:web:b8bd0a4c00f51c1244ebed',
    messagingSenderId: '813260456344',
    projectId: 'carbon-a2574',
    authDomain: 'carbon-a2574.firebaseapp.com',
    storageBucket: 'carbon-a2574.firebasestorage.app',
    measurementId: 'G-M1PEYDHG2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXJwdjrl_gjYBX0mKHptznxlw6X1RIMSM',
    appId: '1:813260456344:android:ae6197c423989b4b44ebed',
    messagingSenderId: '813260456344',
    projectId: 'carbon-a2574',
    storageBucket: 'carbon-a2574.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzcj9yqBjXUE-bsadrKibj0k6cLBUDOV0',
    appId: '1:813260456344:ios:27feaeb1d8baff8b44ebed',
    messagingSenderId: '813260456344',
    projectId: 'carbon-a2574',
    storageBucket: 'carbon-a2574.firebasestorage.app',
    iosBundleId: 'com.example.greenstep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzcj9yqBjXUE-bsadrKibj0k6cLBUDOV0',
    appId: '1:813260456344:ios:27feaeb1d8baff8b44ebed',
    messagingSenderId: '813260456344',
    projectId: 'carbon-a2574',
    storageBucket: 'carbon-a2574.firebasestorage.app',
    iosBundleId: 'com.example.greenstep',
  );
}
